# This workflow uploads website content directly to nginx docker container webroot
# when any pushes to main branch happen
name: Deploy website

on:
  push:
    branches:
      - main
    paths:
      - 'examples/test2/files/s3_bucket_files/**'

env:
  DEPLOY_APP: ${{ vars.DEPLOY_APP }}
  DEPLOY_GROUP: ${{ vars.DEPLOY_GROUP }}

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload website to S3 
        working-directory: examples/test2/files/s3_bucket_files
        run: |
          aws s3 sync . s3://${{ secrets.S3_BUCKET }}

      - name: Deploy changes
        run: |
          aws deploy create-deployment --application-name $DEPLOY_APP \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --deployment-group-name $DEPLOY_GROUP \
            --description "Deploy" \
            --s3-location bucket=${{ secrets.S3_BUCKET }},key=app.zip,bundleType=zip
